{% set name = "email-validator" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JoshData/python-email-validator/archive/v{{ version }}.tar.gz
  sha256: 01498d84bd576c449e476a49aa70722a9aaf2a3b00957d53ddb2f3bec04b0855

build:
  number: 0
  noarch: python
  entry_points:
    - email_validator=email_validator:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - dnspython >=1.15.0
    - idna >=2.0.0
    - pip
    - python
  run:
    - dnspython >=1.15.0
    - idna >=2.0.0
    - python

test:
  source_files:
    - tests
  requires:
    - coverage
    - docutils
    - flake8
    - pytest
    - pytest-cov
  imports:
    - email_validator
  commands:
    - email_validator --help
    - pytest --cov=email_validator

about:
  home: https://github.com/JoshData/python-email-validator
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: A robust email syntax and deliverability validation library for Python 2.x/3.x.
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator

extra:
  recipe-maintainers:
    - xylar
