{% set name = "email-validator" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://github.com/JoshData/python-email-validator/archive/v{{ version }}.tar.gz
  sha256: b7b154e0bce97b7e8063d04ea5bbc4c0b8a51ec55011278e47765578dce9e4b0

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      entry_points:
        - email_validator = email_validator:main
    script: build_email_validator.sh
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - idna >=2.0.0
        - dnspython >=1.15.0
    test:
      source_files:
        - tests
      requires:
        - coverage
        - docutils
        - flake8
        - pytest
        - pytest-cov
      imports:
        - email_validator
      commands:
        - email_validator --help
        - pytest --cov=email_validator

  # Provide package with alternative name for backward compatibility
  - name: email_validator
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('email-validator', max_pin="x.x.x") }}
    test:
      imports:
        - email_validator
      commands:
        - email_validator --help

about:
  home: https://github.com/JoshData/python-email-validator
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: A robust email syntax and deliverability validation library for 3.x.
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator

extra:
  feedstock-name: email-validator
  recipe-maintainers:
    - xylar
    - pmlandwehr
