{% set name = "email-validator" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}-meta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/email_validator-{{ version }}.tar.gz
  sha256: f4904f4145c11f8de5897afbb8d7db4b465c57f13db1c8c106c16d02bceebd9a

build:
  number: 0
  noarch: python

outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      entry_points:
        - email_validator = email_validator.__main__:main
    script: build_email_validator.sh
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - dnspython >=2.0.0
        - idna >=2.0.0
    test:
      source_files:
        - tests
      requires:
        - coverage
        - docutils
        - flake8
        - pytest
        - pytest-cov
      imports:
        - email_validator
      commands:
        - email_validator --help
        - pytest --cov=email_validator

  # Provide package with alternative name for backward compatibility
  - name: email_validator
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('email-validator', max_pin="x.x.x") }}
    test:
      imports:
        - email_validator
      commands:
        - email_validator --help

about:
  home: https://github.com/JoshData/python-email-validator
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: A robust email syntax and deliverability validation library for 3.x.
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator

extra:
  feedstock-name: email-validator
  recipe-maintainers:
    - xylar
    - pmlandwehr
